import type { AgentDefinition } from '../types'

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  // --- Existing agents (updated with category + aliases) ---
  {
    id: 'claude-code',
    name: 'Claude Code',
    projectSkillPath: '.claude/skills',
    globalSkillPath: '~/.claude/skills',
    configFiles: ['CLAUDE.md'],
    configDirs: ['.claude'],
    category: 'agent-specific',
    mcpConfigPath: '.claude/mcp.json',
    globalMcpConfigPath: '~/.claude/mcp.json',
    mcpConfigFormat: 'mcp-servers',
  },
  {
    id: 'claude-cowork',
    name: 'Claude Cowork',
    projectSkillPath: '.claude/skills',
    globalSkillPath: '~/.claude/skills',
    configFiles: ['CLAUDE.md'],
    configDirs: ['.claude'],
    category: 'agent-specific',
    mcpConfigPath: '.claude/mcp.json',
    globalMcpConfigPath: '~/.claude/mcp.json',
    mcpConfigFormat: 'mcp-servers',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    projectSkillPath: '.cursor/skills',
    globalSkillPath: '~/.cursor/skills',
    configFiles: ['.cursorrules'],
    configDirs: ['.cursor'],
    category: 'agent-specific',
    mcpConfigPath: '.cursor/mcp.json',
    globalMcpConfigPath: '~/.cursor/mcp.json',
    mcpConfigFormat: 'mcp-servers',
  },
  {
    id: 'codex',
    name: 'OpenAI Codex',
    projectSkillPath: '.agents/skills',
    globalSkillPath: '~/.codex/skills',
    configFiles: ['AGENTS.md'],
    configDirs: ['.codex', '.agents'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    projectSkillPath: '.opencode/skills',
    globalSkillPath: '~/.config/opencode/skills',
    configFiles: [],
    configDirs: ['.opencode', '.config/opencode'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    projectSkillPath: '.github/skills',
    globalSkillPath: '~/.copilot/skills',
    configFiles: ['.github/copilot-instructions.md'],
    configDirs: [],
    category: 'agent-specific',
    aliases: ['github-copilot'],
    mcpConfigPath: '.vscode/mcp.json',
    globalMcpConfigPath: null,
    mcpConfigFormat: 'vscode-servers',
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    projectSkillPath: '.windsurf/skills',
    globalSkillPath: '~/.codeium/windsurf/skills',
    configFiles: ['.windsurfrules'],
    configDirs: ['.windsurf'],
    category: 'agent-specific',
    mcpConfigPath: '.windsurf/mcp.json',
    globalMcpConfigPath: '~/.windsurf/mcp.json',
    mcpConfigFormat: 'mcp-servers',
  },
  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    projectSkillPath: '.gemini/skills',
    globalSkillPath: '~/.gemini/skills',
    configFiles: ['GEMINI.md'],
    configDirs: ['.gemini'],
    category: 'agent-specific',
    aliases: ['gemini'],
    mcpConfigPath: '.gemini/settings.json',
    globalMcpConfigPath: '~/.gemini/settings.json',
    mcpConfigFormat: 'mcp-servers',
  },
  {
    id: 'roo',
    name: 'Roo Code',
    projectSkillPath: '.roo/skills',
    globalSkillPath: '~/.roo/skills',
    configFiles: ['.roo/rules'],
    configDirs: ['.roo'],
    category: 'agent-specific',
    aliases: ['roo-code'],
    mcpConfigPath: '.roo/mcp.json',
    globalMcpConfigPath: '~/.roo/mcp.json',
    mcpConfigFormat: 'mcp-servers',
  },
  {
    id: 'goose',
    name: 'Goose',
    projectSkillPath: '.goose/skills',
    globalSkillPath: '~/.config/goose/skills',
    configFiles: [],
    configDirs: ['.goose'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'junie',
    name: 'JetBrains Junie',
    projectSkillPath: '.junie/skills',
    globalSkillPath: '~/.junie/skills',
    configFiles: ['.junie/guidelines.md'],
    configDirs: ['.junie'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'aider',
    name: 'Aider',
    projectSkillPath: '.aider/skills',
    globalSkillPath: '~/.aider/skills',
    configFiles: ['.aider.conf.yml'],
    configDirs: ['.aider'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },

  // --- New universal agents (projectSkillPath = .agents/skills) ---
  {
    id: 'amp',
    name: 'Amp',
    projectSkillPath: '.agents/skills',
    globalSkillPath: '~/.config/agents/skills',
    configFiles: [],
    configDirs: [],
    category: 'universal',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'cline',
    name: 'Cline',
    projectSkillPath: '.agents/skills',
    globalSkillPath: '~/.agents/skills',
    configFiles: [],
    configDirs: ['.clinerules'],
    category: 'universal',
    mcpConfigPath: '.cline/mcp_settings.json',
    globalMcpConfigPath: '~/.cline/mcp_settings.json',
    mcpConfigFormat: 'mcp-servers',
  },
  {
    id: 'kimi-cli',
    name: 'Kimi Code CLI',
    projectSkillPath: '.agents/skills',
    globalSkillPath: '~/.config/agents/skills',
    configFiles: [],
    configDirs: ['.kimi'],
    category: 'universal',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'replit',
    name: 'Replit',
    projectSkillPath: '.agents/skills',
    globalSkillPath: '~/.config/agents/skills',
    configFiles: ['.replit'],
    configDirs: [],
    category: 'universal',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'universal',
    name: 'Universal',
    projectSkillPath: '.agents/skills',
    globalSkillPath: '~/.config/agents/skills',
    configFiles: [],
    configDirs: [],
    category: 'universal',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },

  // --- New agent-specific (simple pattern) ---
  {
    id: 'adal',
    name: 'AdaL',
    projectSkillPath: '.adal/skills',
    globalSkillPath: '~/.adal/skills',
    configFiles: [],
    configDirs: ['.adal'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'augment',
    name: 'Augment',
    projectSkillPath: '.augment/skills',
    globalSkillPath: '~/.augment/skills',
    configFiles: [],
    configDirs: ['.augment'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'codebuddy',
    name: 'CodeBuddy',
    projectSkillPath: '.codebuddy/skills',
    globalSkillPath: '~/.codebuddy/skills',
    configFiles: [],
    configDirs: ['.codebuddy'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'command-code',
    name: 'Command Code',
    projectSkillPath: '.commandcode/skills',
    globalSkillPath: '~/.commandcode/skills',
    configFiles: [],
    configDirs: ['.commandcode'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'continue',
    name: 'Continue',
    projectSkillPath: '.continue/skills',
    globalSkillPath: '~/.continue/skills',
    configFiles: [],
    configDirs: ['.continue'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'crush',
    name: 'Crush',
    projectSkillPath: '.crush/skills',
    globalSkillPath: '~/.config/crush/skills',
    configFiles: [],
    configDirs: ['.crush'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'iflow-cli',
    name: 'iFlow CLI',
    projectSkillPath: '.iflow/skills',
    globalSkillPath: '~/.iflow/skills',
    configFiles: [],
    configDirs: ['.iflow'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'kilo',
    name: 'Kilo Code',
    projectSkillPath: '.kilocode/skills',
    globalSkillPath: '~/.kilocode/skills',
    configFiles: [],
    configDirs: ['.kilocode'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'kiro-cli',
    name: 'Kiro CLI',
    projectSkillPath: '.kiro/skills',
    globalSkillPath: '~/.kiro/skills',
    configFiles: [],
    configDirs: ['.kiro'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'kode',
    name: 'Kode',
    projectSkillPath: '.kode/skills',
    globalSkillPath: '~/.kode/skills',
    configFiles: [],
    configDirs: ['.kode'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'mcpjam',
    name: 'MCPJam',
    projectSkillPath: '.mcpjam/skills',
    globalSkillPath: '~/.mcpjam/skills',
    configFiles: [],
    configDirs: ['.mcpjam'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'mistral-vibe',
    name: 'Mistral Vibe',
    projectSkillPath: '.vibe/skills',
    globalSkillPath: '~/.vibe/skills',
    configFiles: [],
    configDirs: ['.vibe'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'mux',
    name: 'Mux',
    projectSkillPath: '.mux/skills',
    globalSkillPath: '~/.mux/skills',
    configFiles: [],
    configDirs: ['.mux'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'neovate',
    name: 'Neovate',
    projectSkillPath: '.neovate/skills',
    globalSkillPath: '~/.neovate/skills',
    configFiles: [],
    configDirs: ['.neovate'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'openhands',
    name: 'OpenHands',
    projectSkillPath: '.openhands/skills',
    globalSkillPath: '~/.openhands/skills',
    configFiles: [],
    configDirs: ['.openhands'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'pochi',
    name: 'Pochi',
    projectSkillPath: '.pochi/skills',
    globalSkillPath: '~/.pochi/skills',
    configFiles: [],
    configDirs: ['.pochi'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'qoder',
    name: 'Qoder',
    projectSkillPath: '.qoder/skills',
    globalSkillPath: '~/.qoder/skills',
    configFiles: [],
    configDirs: ['.qoder'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'qwen-code',
    name: 'Qwen Code',
    projectSkillPath: '.qwen/skills',
    globalSkillPath: '~/.qwen/skills',
    configFiles: [],
    configDirs: ['.qwen'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'trae',
    name: 'Trae',
    projectSkillPath: '.trae/skills',
    globalSkillPath: '~/.trae/skills',
    configFiles: [],
    configDirs: ['.trae'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'trae-cn',
    name: 'Trae CN',
    projectSkillPath: '.trae/skills',
    globalSkillPath: '~/.trae-cn/skills',
    configFiles: [],
    configDirs: ['.trae-cn'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'zencoder',
    name: 'Zencoder',
    projectSkillPath: '.zencoder/skills',
    globalSkillPath: '~/.zencoder/skills',
    configFiles: [],
    configDirs: ['.zencoder'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: '~/.zencoder/mcp.json',
    mcpConfigFormat: 'mcp-servers',
  },

  // --- New agent-specific (unusual paths) ---
  {
    id: 'antigravity',
    name: 'Antigravity',
    projectSkillPath: '.agent/skills',
    globalSkillPath: '~/.gemini/antigravity/skills',
    configFiles: [],
    configDirs: ['.gemini/antigravity'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'cortex',
    name: 'Cortex Code',
    projectSkillPath: '.cortex/skills',
    globalSkillPath: '~/.snowflake/cortex/skills',
    configFiles: [],
    configDirs: ['.cortex'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'droid',
    name: 'Droid',
    projectSkillPath: '.factory/skills',
    globalSkillPath: '~/.factory/skills',
    configFiles: [],
    configDirs: ['.factory'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    projectSkillPath: 'skills',
    globalSkillPath: '~/.openclaw/skills',
    configFiles: [],
    configDirs: ['.openclaw'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
  {
    id: 'pi',
    name: 'Pi',
    projectSkillPath: '.pi/skills',
    globalSkillPath: '~/.pi/agent/skills',
    configFiles: [],
    configDirs: ['.pi'],
    category: 'agent-specific',
    mcpConfigPath: null,
    globalMcpConfigPath: null,
    mcpConfigFormat: null,
  },
]

export const AGENT_MAP = new Map(AGENT_DEFINITIONS.map((a) => [a.id, a]))

/** Get agents that support MCP server configuration */
export function getMcpCapableAgents(): AgentDefinition[] {
  return AGENT_DEFINITIONS.filter((a) => a.mcpConfigPath !== null || a.globalMcpConfigPath !== null)
}
