#!/usr/bin/env bash
# =============================================================================
# Agentver — Self-Hosted Setup
# =============================================================================
# Interactive script that generates .env, pulls images, and starts services.
# Run from the docker/ directory: ./setup.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== Agentver Self-Hosted Setup ==="
echo ""

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------
command -v docker >/dev/null 2>&1 || { echo "Error: Docker is required. Install it from https://docs.docker.com/get-docker/"; exit 1; }
command -v docker compose >/dev/null 2>&1 || { echo "Error: Docker Compose v2 is required."; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo "Error: openssl is required for secret generation."; exit 1; }

# Check for existing .env
if [[ -f .env ]]; then
  echo "An existing .env file was found."
  read -rp "Overwrite it? (y/N): " OVERWRITE
  if [[ "${OVERWRITE,,}" != "y" ]]; then
    echo "Setup cancelled. Edit .env manually or delete it and re-run."
    exit 0
  fi
  echo ""
fi

# ---------------------------------------------------------------------------
# Generate secrets
# ---------------------------------------------------------------------------
POSTGRES_PASSWORD=$(openssl rand -base64 24)
BETTER_AUTH_SECRET=$(openssl rand -base64 32)
TOKEN_ENCRYPTION_KEY=$(openssl rand -hex 32)

# ---------------------------------------------------------------------------
# Gather configuration
# ---------------------------------------------------------------------------
read -rp "Public URL [http://localhost:3000]: " APP_URL
APP_URL=${APP_URL:-http://localhost:3000}

PROFILES=""

echo ""
read -rp "Include git server (Forgejo) for full version control? (y/N): " INCLUDE_GIT
if [[ "${INCLUDE_GIT,,}" == "y" ]]; then
  PROFILES="--profile git"
fi

read -rp "Include Redis for caching? (y/N): " INCLUDE_REDIS
if [[ "${INCLUDE_REDIS,,}" == "y" ]]; then
  PROFILES="$PROFILES --profile cache"
fi

# ---------------------------------------------------------------------------
# Write .env
# ---------------------------------------------------------------------------
cat > .env << EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATABASE_URL=postgresql://agentver:${POSTGRES_PASSWORD}@postgres:5432/agentver
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
APP_URL=${APP_URL}
NEXT_PUBLIC_APP_URL=${APP_URL}
EMAIL_PROVIDER=console
STORAGE_ADAPTER=local
EOF

if [[ "${INCLUDE_REDIS,,}" == "y" ]]; then
  echo "REDIS_URL=redis://redis:6379" >> .env
fi

echo ""
echo "Configuration written to .env"
echo ""

# ---------------------------------------------------------------------------
# Start services
# ---------------------------------------------------------------------------
echo "Starting Agentver..."
docker compose $PROFILES up -d

echo ""
echo "=== Setup Complete ==="
echo ""
echo "  Dashboard:  ${APP_URL}"
echo "  Create your first account at: ${APP_URL}/sign-up"
echo ""
echo "  Useful commands:"
echo "    docker compose logs -f app     # View application logs"
echo "    docker compose down            # Stop all services"
echo "    docker compose pull && docker compose up -d  # Update"
echo ""
